name: Node CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2.0.0
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

